set(SDKCONFIG_DEFAULTS "${CMAKE_CURRENT_LIST_DIR}/sdkconfig.defaults")
set(SDKCONFIG "${CMAKE_CURRENT_LIST_DIR}/sdkconfig")

set(HW_INFO_DIR ${CMAKE_CURRENT_LIST_DIR}/include)
set(HW_INIT_SRC ${CMAKE_CURRENT_LIST_DIR}/src/hw_init.c)
set(RUNNER_PROFILE_FILE ${CMAKE_CURRENT_LIST_DIR}/run.json)