#include <gtest/gtest.h>
#include <cstdint>

#include <pubsub/Publisher.h>
#include <pubsub/Subscriber.h>
#include <pubsub/RPCHandler.h>
#include <pubsub/RPCRequest.h>
#include <pubsub/Topics.h>

// sys_assert_handler() (firmware/src/lib/debug/sys_assert.c) calls abort(). This test build runs
// CMAKE_BUILD_TYPE=Debug, so SYS_ASSERT is live and invalid usage below genuinely aborts, which is
// what EXPECT_DEATH expects. In a release (NDEBUG) build these asserts are no-ops. hal_stdio_printf
// writes to stdout not stderr, so EXPECT_DEATH matches "" rather than the assert text.

// Never reuse a Topics.h production topic across tests: Publisher's constructor enforces single
// ownership per topic, and topic identity is the tag struct type generated by
// PUBSUB_REGISTER_TOPIC(_SIZE)/PUBSUB_REGISTER_RPC, not a runtime handle.

namespace
{
    struct RoundTripMsg
    {
        int value;
        float extra;
    };
    PUBSUB_REGISTER_TOPIC_SIZE(RoundTripMsg, test_round_trip, 4)
}

TEST(MessageBus, PublishThenPollRoundTrip)
{
    PubSub::Publisher<test_round_trip_topic> pub;
    PubSub::Subscriber<test_round_trip_topic> sub;

    EXPECT_FALSE(sub.poll());

    pub.publish({42, 3.5f});

    ASSERT_TRUE(sub.poll());
    EXPECT_EQ(sub.get().value, 42);
    EXPECT_FLOAT_EQ(sub.get().extra, 3.5f);

    EXPECT_FALSE(sub.poll());
}

namespace
{
    struct EmptyPollMsg
    {
        int value;
    };
    PUBSUB_REGISTER_TOPIC_SIZE(EmptyPollMsg, test_empty_poll, 4)
}

TEST(MessageBus, PollWithNoNewDataLeavesLastValueUntouched)
{
    PubSub::Publisher<test_empty_poll_topic> pub;
    PubSub::Subscriber<test_empty_poll_topic> sub;

    pub.publish({7});
    ASSERT_TRUE(sub.poll());
    EXPECT_EQ(sub.get().value, 7);

    EXPECT_FALSE(sub.poll());
    EXPECT_EQ(sub.get().value, 7);

    EXPECT_FALSE(sub.poll());
    EXPECT_EQ(sub.get().value, 7);
}

namespace
{
    struct LatestMsg
    {
        int seq;
    };
    PUBSUB_REGISTER_TOPIC_SIZE(LatestMsg, test_latest, 4)
}

TEST(MessageBus, PollLatestReturnsNewestAndCatchesUp)
{
    PubSub::Publisher<test_latest_topic> pub;
    PubSub::Subscriber<test_latest_topic> sub;

    for (int i = 0; i < 3; i++)
    {
        pub.publish({i});
    }

    ASSERT_TRUE(sub.pollLatest());
    EXPECT_EQ(sub.get().seq, 2);

    EXPECT_FALSE(sub.poll());
    EXPECT_FALSE(sub.pollLatest());

    pub.publish({99});

    ASSERT_TRUE(sub.pollLatest());
    EXPECT_EQ(sub.get().seq, 99);
}

namespace
{
    struct SlowMsg
    {
        int seq;
    };
    PUBSUB_REGISTER_TOPIC_SIZE(SlowMsg, test_too_slow, 4)
}

TEST(MessageBusDeathTest, PollWhenLappedBySlowSubscriberAsserts)
{
    PubSub::Publisher<test_too_slow_topic> pub;
    PubSub::Subscriber<test_too_slow_topic> sub;

    for (int i = 0; i < 5; i++) // depth is 4; one extra publish laps the reader
    {
        pub.publish({i});
    }

    EXPECT_DEATH(sub.poll(), "");
}

// CreateHandleWithMismatchedMessageSizeAsserts and AdvertiseTopicNonPowerOfTwoCountAsserts from the
// old runtime registry have no equivalent here: message size and depth are now enforced by
// static_assert inside TopicStorage, so both are compile errors rather than a runtime path
// EXPECT_DEATH could exercise.

namespace
{
    struct DoubleOwnerMsg
    {
        int value;
    };
    PUBSUB_REGISTER_TOPIC_SIZE(DoubleOwnerMsg, test_double_owner, 4)
}

TEST(MessageBusDeathTest, SecondPublisherConstructionAsserts)
{
    PubSub::Publisher<test_double_owner_topic> pub1;

    EXPECT_DEATH({ PubSub::Publisher<test_double_owner_topic> pub2; }, "");
}

namespace
{
    struct RpcTestRequest
    {
        int32_t requestValue;
    };
    PUBSUB_REGISTER_RPC(RpcTestRequest, test_rpc)
}

TEST(MessageBusRPC, RequestHandlerRoundTrip)
{
    PubSub::RPCHandler<test_rpc_req_topic, test_rpc_res_topic> handler;
    PubSub::RPCRequest<test_rpc_req_topic, test_rpc_res_topic> requester;

    EXPECT_FALSE(handler.requestAvailable());

    requester.call({123}, /*src=*/7);

    ASSERT_TRUE(handler.requestAvailable());
    EXPECT_EQ(handler.getRequestData().requestValue, 123);

    handler.sendResponse(true);

    ASSERT_TRUE(requester.finished());
    EXPECT_TRUE(requester.isSuccess());
    EXPECT_EQ(requester.getResponseSource(), 7);
}

// Subscriber::copyData's torn-read retry loop is not covered: exercising it needs a publish to land
// between the reader's copy and its post-copy re-check of write_sequence, which requires real
// concurrent execution with no test hook available in Subscriber as currently written.
