#pragma once

/* General */
#define EKF_RATE_HZ 250
#define EKF_MAX_FUSIONS_PER_UPDATE 10
#define EKF_INIT_ACC_MAG_ERROR_THRESHOLD 0.5f
#define EKF_USE_MAG 1
#define EKF_FAST_INIT 1

#if !EKF_FAST_INIT
#define EKF_INIT_IMU_SAMPLES 200
#else
#define EKF_INIT_IMU_SAMPLES 1
#endif

/** Delay horizon */
#define EKF_DELAY_HORIZON_MS 200
#define EKF_IMU_DELAY_HORIZON_SIZE 60
#define EKF_GPS_DELAY_HORIZON_SIZE 10
#define EKF_BARO_DELAY_HORIZON_SIZE 20
#define EKF_MAG_DELAY_HORIZON_SIZE 30

/** Sensor delays */
#define EKF_GPS_DELAY_MS 100
#define EKF_BARO_DELAY_MS 20
#define EKF_MAG_DELAY_MS 10

/** Gate thresholds */
#define EKF_GATE_THRESHOLD_GPS_POS 6.0f
#define EKF_GATE_THRESHOLD_GPS_VEL 6.0f
#define EKF_GATE_THRESHOLD_BARO 6.0f
#define EKF_GATE_THRESHOLD_MAG 6.0f

/** Covariance Init */
#define EKF_COV_DEFAULT_ATT_ROLL_PITCH 0.001f
#define EKF_COV_DEFAULT_ATT_YAW 0.001f
#define EKF_COV_DEFAULT_VEL 0.01f
#define EKF_COV_DEFAULT_POS 0.01f
#define EKF_COV_DEFAULT_MAG 0.00001f
#define EKF_COV_DEFAULT_B_ACC 0.00001f
#define EKF_COV_DEFAULT_B_GYRO 0.00001f
#define EKF_COV_DEFAULT_B_MAG 0.000001f

/** Noises */
#define EKF_NOISE_ACC 0.055f
#define EKF_NOISE_ACC_CLIPPING 0.6f
#define EKF_NOISE_GYRO 0.17f
#define EKF_NOISE_GYRO_CLIPPING 0.9f
#define EKF_NOISE_ACC_BIAS 0.0001f
#define EKF_NOISE_GYRO_BIAS 0.0001f
#define EKF_NOISE_BARO 0.4f
#define EKF_NOISE_MAG 0.0004f
#define EKF_NOISE_MAG_BIAS 0.000000001f

/** Output Predictor Time Constants */
#define EKF_OUTPUT_PREDICTOR_ATT_TAU 0.2f
#define EKF_OUTPUT_PREDICTOR_VEL_TAU 0.25f
#define EKF_OUTPUT_PREDICTOR_POS_TAU 0.25f

/** Other */
#define EKF_GPS_FUSION_VELOCITY_THRESHOLD 1.0f
#define EKF_GPS_VEL_D_NOISE_SCALE 3.0f