#pragma once

#define IGN_COUNT 4

#define IGN_UP_TIME_MS 10
#define IGN_CONTINUITY_DEAD_TIME 500
#define MAIN_PARACHUTE_HEIGHT 200
#define MALFUNCTION_SPEED 20

#define IGN_FUSE_WORKING_IGN_PRESENT_FACTOR 0
#define IGN_FUSE_WORKING_IGN_NOT_PRESENT_FACTOR 0.0189607f
#define IGN_FUSE_NOT_WORKING_IGN_PRESENT_FACTOR 0.0297897f
#define IGN_FUSE_NOT_WORKING_IGN_NOT_PRESENT_FACTOR 0.0383104f
#define IGN_FUSE_CHECK_EPS 0.005f