add_compile_definitions(
    BOARD_FLASH_PAGE_SIZE=256
    BOARD_FLASH_SECTOR_SIZE=4096
    BOARD_FLASH_SIZE=2097152
)

set(HW_INFO_DIR ${CMAKE_CURRENT_LIST_DIR}/include)
set(HW_INIT_SRC ${CMAKE_CURRENT_LIST_DIR}/src/hw_init.c)
set(RUNNER_PROFILE_FILE ${CMAKE_CURRENT_LIST_DIR}/run.json)