name: DataLink C# Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  csharp-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./datalink

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Generate C# code for tests
        run: python gen.py --lang csharp --outdir tests/csharp

      - name: Run C# tests
        run: dotnet run --project tests/csharp/TestRuntime.csproj
