name: Build Firmware

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compile:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./firmware

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Toolchain
        run: sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential ninja-build

      - name: Build 'obc'
        run: |
          make obc

      - name: Build 'obc_sitl'
        run: |
          make obc_sitl

      - name: Build 'radio_module'
        run: |
          make radio_module

      - name: Build 'radio_module_sitl'
        run: |
          make radio_module_sitl

      - name: Run tests
        run: |
          make test
